### ISSUE TITLE
gnpy doesn't work after the installation

### ISSUE THREAD

**Issue by aleFerrari** [Telecominfraproject/gnpy#2]
* gnpy version: 0.1.0
* Python version: 2.7.13 and 3.6.1
* Operating System: Fedora 26

### What I Did

I installed gnpy using python  2.7.13 with the command
`sudo python setup.py clean build -f install`
then I  run the program with the command
`gnpy`
and the output is the following;
> Replace this message by putting your code into gnpy.cli.main
See click documentation at http://click.pocoo.org/

I tried also using python3 but the output is the same

**Comment by giladg-FB** [comment]
should be fixed on develop.
Please pull and checkout develop branch. To install gnpy execute `pip install </path_to_gnpy_repo>`. __main__.py should execute. Please describe any more issues - if ok i'll merge to master since this is fundamental functionality and doesn't require further approval.

**Comment by aleFerrari** [comment]
Ok. Running the command `pip install </path_to_gnpy_repo>` and then executing `python __main__.py` the program runs.
