### ISSUE TITLE
'uid' generated by .xls to .json parser

### ISSUE THREAD

**Issue by berahtlv** [Telecominfraproject/gnpy#60]
.xls to .json parser generates 'uid' with blanks, because of that source and sink can not be addressed correctly by running transmission_main_example.py

**Comment by jeanluc-auge** [comment]
Thank you for taking the time to test the code,
I did not reproduce the issue that you describe: could you please give the exact command line you typed and check that you use the latest develop branch update (there are a lot of recent PR related to the xls parser)?
Also, while it's still possible to launch the convert.py parser independantly, you can also launch the transmission_main_example.py <toplogy.xls> directly, just like 
transmission_main_example.py <toplogy.json>

**Comment by berahtlv** [comment]
It's my fault, I've tried:
```
> python transmission_main_example.py network.xls NodeA NodeB
parse excel input to network.json
invalid souce node specified: 'NodeA', replaced with Transceiver trx NodeA
invalid destination node specified: 'NodeB', replaced with Transceiver trx NodeB
```
Can be solved using quotation marks:
```
> python transmission_main_example.py network.xls 'trx NodeA' 'trx NodeB'
```
