### ISSUE TITLE
gnpy-gui interface and framework

### ISSUE THREAD

**Issue by berahtlv** [Telecominfraproject/gnpy#61]
It will be great to have GNS3 like interface with according icons of elements, GNPY model already defines elements stand-alone like. In that case network could be imported from JSON/XLS.

Does this project is planning to introduce GUI interface?
What kind of framework would be preferred?

**Comment by dutc** [comment]
Our current focus is developing functionality around the library itself. A GUI is currently outside of the scope of our work. 

However, if code contributors want to focus on writing a GUI, it could generate output in the form of JSON, and we can discuss ensuring that this JSON format remains stable.
